### ISSUE TITLE
 0x200b

### ISSUE THREAD

**Issue by delthas** [emersion/holiday-gift_2013-04#1] opened 2016-10-18 23:52 UTC
-----BEGIN PGP MESSAGE-----
wcFMAxDQGDNaC12OAQ/9GpYATl9Xbkw14L/rKrLX/Eg3t6gfb8NWPbZk3nxp943b
pASavmXQCxIMOHfVbVPAfDqzKHLSA5slTeVkMbvAWRDaWAIqeicoCpEYh4BQKQzq
vqXvvRgN2IrETLEmPtKD44j9ojsxQZY8qvFNb2IizJmljHWKZ4mrbhwU7Uq+Cofn
0OvOZX/TEfUIQuVkGmki4ltyylZpuUCr5rR3BVfui4jrAK8vldCLhFbhga0Dfi6v
qzoaYnM/s/6EqtPU4Zr78fQLan5awpc1xrqQFEN+pDTZgoUUv0fagxhokSUl+pf5
CHuxfQGVCCFmW8h1KaE7+Hk92MgtrWvKlf+ui7jAX9wggwbXnfQJj3AIuhAe2gQ1
ySZ1sGOqoUAHF1sOkuYWlCIRlWJC5WDV85/11aaMjDkLBm8heymMzOlzcMsOtXED
8CvGIsiue707zhnv2gtpLHODIHC0KUhmEsxy+CWkx13UqBjTigHmfsMaE8fz/QGR
u7bO+Pzyeg9np9O3ny7N8kZS52uGW3erXec4XQVol9tpu4J6Ug9QD9hz9Zi6ummn
8BPfIOMYgR0vkQBtiyf6FC5mXt+J+Pizwq4xP0xWNJG2xDCEOPqegD+GRXOdlzrR
of1KLT0MwgPQkh66OFtIP4I9Zlch+xyN+q9ognAT5ncq6OZxkaHkQQRx5rWHW7/S
QwH1k3ityO0Yvk0Uh0Q4KrgW2fgIdR1rZiYLm6RxbL0dbdVZdQzmjrenQypI4vle
beBQqzS4oGiivVCB+dOze1azLZU=
=34xv
-----END PGP MESSAGE-----

**Comment by emersion** [comment] 2016-10-19 06:05
Duplicate of https://github.com/Delthas/tacotac/issues/1

**Closed as completed by emersion** 2016-10-19 06:05 UTC
